Gzip payload before upload
mmarinm/sumologrus pull request #13
Opened 2020-10-02 23:54 UTC by vigneshashokan

Compress (gzip) payload before upload.

2020-10-04 03:50 UTC, mmarinm requested changes
Thanks for the PR.
Can you please fix the tests?
I think it will be good if compression can be turned off optionally in configuration. In case someone wants real time logs and they limit batch size to 1, payload size might be so small that is not even worth it to waste CPU on compression.

2020-10-04 03:50 UTC, mmarinm commented on hook.go
> +		return err
I think it will be good to log error so user is aware what went wrong with uploading log
`h.errorf("compressing  payload - %s", err)`

2020-10-04 03:50 UTC, mmarinm commented on hook.go
> +		return err
same like above log error

2020-10-06 14:34 UTC, vigneshashokan commented
> Thanks for the PR.
> Can you please fix the tests?
> Can you please set appropriate header for gzip `req.Header.Set("Content-Encoding", "gzip")`
> I think it will be good if compression can be turned off optionally in configuration. In case someone wants real time logs and they limit batch size to 1, payload size might be so small that is not even worth it to waste CPU on compression.

I refactored code a bit, added error loggers and fixed the UTs. Turning off compression optionally is added work and I feel is out of scope for this issue. Work might be small, but we need to add more UTs for that as well, so I didn't do that. However I'm open to working on that in a different PR, if that's okay with you. Let me know what you think.

2020-10-12 01:26 UTC, merged

2020-10-12 23:52 UTC, vigneshashokan commented
Hey @mmarinm. Thanks for accepting my PR. If it isn't too much trouble, I would appreciate if you can add `hacktoberfest-accepted` label to this PR (https://hacktoberfest.digitalocean.com/hacktoberfest-update)